
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOK1 = 6;
  public static final int INT = 12;
  public static final int STR = 13;
  public static final int STRINGS = 10;
  public static final int V = 3;
  public static final int USER = 14;
  public static final int PV = 2;
  public static final int EOF = 0;
  public static final int ARROW = 5;
  public static final int DOUBLE = 15;
  public static final int SEP = 11;
  public static final int AUC = 8;
  public static final int error = 1;
  public static final int DP = 4;
  public static final int MIN = 9;
  public static final int TOK2 = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PV",
  "V",
  "DP",
  "ARROW",
  "TOK1",
  "TOK2",
  "AUC",
  "MIN",
  "STRINGS",
  "SEP",
  "INT",
  "STR",
  "USER",
  "DOUBLE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[6]=new String("TOK1");
		TT[12]=new String("INT");
		TT[13]=new String("STR");
		TT[10]=new String("STRINGS");
		TT[3]=new String("V");
		TT[14]=new String("USER");
		TT[2]=new String("PV");
		TT[0]=new String("EOF");
		TT[5]=new String("ARROW");
		TT[15]=new String("DOUBLE");
		TT[11]=new String("SEP");
		TT[8]=new String("AUC");
		TT[1]=new String("error");
		TT[4]=new String("DP");
		TT[9]=new String("MIN");
		TT[7]=new String("TOK2");
	}
public String getTT(int i){return TT[i];}
}

