
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUS = 14;
  public static final int INT = 19;
  public static final int TC = 13;
  public static final int TA = 12;
  public static final int STAR = 16;
  public static final int END = 7;
  public static final int WITH = 8;
  public static final int PV = 9;
  public static final int COMPARE = 6;
  public static final int EOF = 0;
  public static final int DIVIDE = 17;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int MINUS = 15;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int GC = 11;
  public static final int EQ = 18;
  public static final int GA = 10;
  public static final int VAR = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "PRINT",
  "COMPARE",
  "END",
  "WITH",
  "PV",
  "GA",
  "GC",
  "TA",
  "TC",
  "PLUS",
  "MINUS",
  "STAR",
  "DIVIDE",
  "EQ",
  "INT",
  "VAR"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[14]=new String("PLUS");
		TT[19]=new String("INT");
		TT[13]=new String("TC");
		TT[12]=new String("TA");
		TT[16]=new String("STAR");
		TT[7]=new String("END");
		TT[8]=new String("WITH");
		TT[9]=new String("PV");
		TT[6]=new String("COMPARE");
		TT[0]=new String("EOF");
		TT[17]=new String("DIVIDE");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[15]=new String("MINUS");
		TT[5]=new String("PRINT");
		TT[1]=new String("error");
		TT[11]=new String("GC");
		TT[18]=new String("EQ");
		TT[10]=new String("GA");
		TT[20]=new String("VAR");
	}
public String getTT(int i){return TT[i];}
}

