
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.HashMap;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\114\000\002\002\004\000\002\002\004\000\002\020" +
    "\004\000\002\020\002\000\002\021\005\000\002\021\005" +
    "\000\002\024\003\000\002\024\003\000\002\022\003\000" +
    "\002\032\002\000\002\022\006\000\002\023\003\000\002" +
    "\023\006\000\002\003\004\000\002\003\003\000\002\003" +
    "\004\000\002\004\003\000\002\004\003\000\002\004\006" +
    "\000\002\004\005\000\002\004\004\000\002\030\011\000" +
    "\002\030\003\000\002\030\003\000\002\030\003\000\002" +
    "\030\005\000\002\031\006\000\002\031\011\000\002\005" +
    "\004\000\002\005\006\000\002\005\006\000\002\005\006" +
    "\000\002\006\005\000\002\006\005\000\002\007\011\000" +
    "\002\007\006\000\002\007\011\000\002\026\005\000\002" +
    "\026\005\000\002\026\005\000\002\026\005\000\002\015" +
    "\002\000\002\016\002\000\002\017\006\000\002\027\005" +
    "\000\002\027\005\000\002\027\005\000\002\027\005\000" +
    "\002\014\002\000\002\013\005\000\002\013\005\000\002" +
    "\013\004\000\002\013\006\000\002\013\005\000\002\013" +
    "\005\000\002\013\005\000\002\013\005\000\002\013\005" +
    "\000\002\013\005\000\002\013\005\000\002\013\005\000" +
    "\002\013\005\000\002\013\003\000\002\013\003\000\002" +
    "\013\003\000\002\013\004\000\002\013\004\000\002\013" +
    "\005\000\002\010\003\000\002\010\003\000\002\011\003" +
    "\000\002\011\003\000\002\012\003\000\002\012\006\000" +
    "\002\012\006\000\002\012\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\216\000\022\003\ufffe\006\ufffe\007\ufffe\010\ufffe\013" +
    "\ufffe\016\ufffe\042\ufffe\043\ufffe\001\002\000\022\003\023" +
    "\006\022\007\014\010\013\013\015\016\026\042\025\043" +
    "\007\001\002\000\004\002\006\001\002\000\004\002\001" +
    "\001\002\000\006\003\ufffa\013\ufffa\001\002\000\024\002" +
    "\uffe9\003\uffe9\006\uffe9\007\uffe9\010\uffe9\012\uffe9\013\uffe9" +
    "\016\uffe9\017\uffe9\001\002\000\022\003\uffff\006\uffff\007" +
    "\uffff\010\uffff\013\uffff\016\uffff\042\uffff\043\uffff\001\002" +
    "\000\006\003\207\013\205\001\002\000\006\003\171\014" +
    "\172\001\002\000\006\003\140\014\141\001\002\000\044" +
    "\003\uffb9\015\uffb9\020\uffb9\022\132\024\uffb9\025\uffb9\026" +
    "\uffb9\027\uffb9\030\uffb9\031\uffb9\032\uffb9\033\uffb9\034\uffb9" +
    "\035\uffb9\036\uffb9\037\uffb9\040\uffb9\001\002\000\020\002" +
    "\000\003\117\006\022\007\014\010\013\013\015\016\026" +
    "\001\002\000\024\002\uffeb\003\uffeb\006\uffeb\007\uffeb\010" +
    "\uffeb\012\uffeb\013\uffeb\016\uffeb\017\uffeb\001\002\000\006" +
    "\020\125\036\124\001\002\000\024\002\uffea\003\uffea\006" +
    "\uffea\007\uffea\010\uffea\012\uffea\013\uffea\016\uffea\017\uffea" +
    "\001\002\000\006\003\120\013\015\001\002\000\024\003" +
    "\117\006\022\007\014\010\013\013\015\016\026\020\037" +
    "\023\041\036\036\001\002\000\024\002\ufff1\003\ufff1\006" +
    "\ufff1\007\ufff1\010\ufff1\012\ufff1\013\ufff1\016\ufff1\017\ufff1" +
    "\001\002\000\006\003\ufffb\013\ufffb\001\002\000\016\003" +
    "\031\006\022\007\014\010\013\013\015\016\026\001\002" +
    "\000\024\002\ufff0\003\ufff0\006\ufff0\007\ufff0\010\ufff0\012" +
    "\ufff0\013\ufff0\016\ufff0\017\ufff0\001\002\000\022\002\ufff3" +
    "\003\ufff3\006\ufff3\007\ufff3\010\ufff3\013\ufff3\016\ufff3\017" +
    "\ufff3\001\002\000\026\003\117\006\022\007\014\010\013" +
    "\013\015\016\026\017\115\020\037\023\041\036\036\001" +
    "\002\000\020\003\035\006\022\007\014\010\013\013\015" +
    "\016\026\017\033\001\002\000\024\002\uffe8\003\uffe8\006" +
    "\uffe8\007\uffe8\010\uffe8\012\uffe8\013\uffe8\016\uffe8\017\uffe8" +
    "\001\002\000\022\002\ufff4\003\ufff4\006\ufff4\007\ufff4\010" +
    "\ufff4\013\ufff4\016\ufff4\017\ufff4\001\002\000\012\017\040" +
    "\020\037\023\041\036\036\001\002\000\020\003\050\004" +
    "\044\005\047\013\015\014\042\025\043\041\051\001\002" +
    "\000\024\002\uffed\003\uffed\006\uffed\007\uffed\010\uffed\012" +
    "\uffed\013\uffed\016\uffed\017\uffed\001\002\000\024\002\uffef" +
    "\003\uffef\006\uffef\007\uffef\010\uffef\012\uffef\013\uffef\016" +
    "\uffef\017\uffef\001\002\000\042\003\uffb6\015\uffb6\020\uffb6" +
    "\024\uffb6\025\uffb6\026\uffb6\027\uffb6\030\uffb6\031\uffb6\032" +
    "\uffb6\033\uffb6\034\uffb6\035\uffb6\036\uffb6\037\uffb6\040\uffb6" +
    "\001\002\000\020\003\112\004\044\005\047\013\015\014" +
    "\042\025\043\041\051\001\002\000\006\004\110\005\107" +
    "\001\002\000\042\003\uffc2\015\uffc2\020\uffc2\024\uffc2\025" +
    "\uffc2\026\uffc2\027\uffc2\030\uffc2\031\uffc2\032\uffc2\033\uffc2" +
    "\034\uffc2\035\uffc2\036\uffc2\037\uffc2\040\uffc2\001\002\000" +
    "\042\003\uffc3\015\uffc3\020\uffc3\024\uffc3\025\uffc3\026\uffc3" +
    "\027\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\034\uffc3\035" +
    "\uffc3\036\uffc3\037\uffc3\040\uffc3\001\002\000\036\020\106" +
    "\024\063\025\054\026\061\027\064\030\070\031\066\032" +
    "\057\033\056\034\065\035\055\036\062\037\053\040\067" +
    "\001\002\000\042\003\uffc1\015\uffc1\020\uffc1\024\uffc1\025" +
    "\uffc1\026\uffc1\027\uffc1\030\uffc1\031\uffc1\032\uffc1\033\uffc1" +
    "\034\uffc1\035\uffc1\036\uffc1\037\uffc1\040\uffc1\001\002\000" +
    "\004\023\041\001\002\000\020\003\050\004\044\005\047" +
    "\013\015\014\042\025\043\041\051\001\002\000\042\003" +
    "\uffce\015\uffce\020\uffce\024\063\025\054\026\061\027\064" +
    "\030\070\031\066\032\057\033\056\034\065\035\055\036" +
    "\062\037\uffce\040\uffce\001\002\000\020\003\050\004\044" +
    "\005\047\013\015\014\042\025\043\041\051\001\002\000" +
    "\020\003\050\004\044\005\047\013\015\014\042\025\043" +
    "\041\051\001\002\000\020\003\uffba\004\uffba\005\uffba\013" +
    "\uffba\014\uffba\025\uffba\041\uffba\001\002\000\020\003\uffbc" +
    "\004\uffbc\005\uffbc\013\uffbc\014\uffbc\025\uffbc\041\uffbc\001" +
    "\002\000\020\003\uffbd\004\uffbd\005\uffbd\013\uffbd\014\uffbd" +
    "\025\uffbd\041\uffbd\001\002\000\020\003\050\004\044\005" +
    "\047\013\015\014\042\025\043\041\051\001\002\000\020" +
    "\003\050\004\044\005\047\013\015\014\042\025\043\041" +
    "\051\001\002\000\004\036\100\001\002\000\020\003\050" +
    "\004\044\005\047\013\015\014\042\025\043\041\051\001" +
    "\002\000\020\003\050\004\044\005\047\013\015\014\042" +
    "\025\043\041\051\001\002\000\020\003\uffbb\004\uffbb\005" +
    "\uffbb\013\uffbb\014\uffbb\025\uffbb\041\uffbb\001\002\000\020" +
    "\003\050\004\044\005\047\013\015\014\042\025\043\041" +
    "\051\001\002\000\020\003\050\004\044\005\047\013\015" +
    "\014\042\025\043\041\051\001\002\000\020\003\050\004" +
    "\044\005\047\013\015\014\042\025\043\041\051\001\002" +
    "\000\020\003\050\004\044\005\047\013\015\014\042\025" +
    "\043\041\051\001\002\000\042\003\uffca\015\uffca\020\uffca" +
    "\024\063\025\054\026\061\027\064\030\070\031\066\032" +
    "\057\033\056\034\065\035\055\036\062\037\053\040\067" +
    "\001\002\000\042\003\uffcc\015\uffcc\020\uffcc\024\063\025" +
    "\054\026\061\027\064\030\uffcc\031\uffcc\032\uffcc\033\uffcc" +
    "\034\uffcc\035\uffcc\036\uffcc\037\uffcc\040\uffcc\001\002\000" +
    "\042\003\uffcf\015\uffcf\020\uffcf\024\063\025\054\026\061" +
    "\027\064\030\070\031\066\032\057\033\056\034\065\035" +
    "\055\036\062\037\053\040\uffcf\001\002\000\042\003\uffcb" +
    "\015\uffcb\020\uffcb\024\063\025\054\026\061\027\064\030" +
    "\uffcb\031\uffcb\032\uffcb\033\uffcb\034\uffcb\035\uffcb\036\uffcb" +
    "\037\uffcb\040\uffcb\001\002\000\042\003\uffc5\015\uffc5\020" +
    "\uffc5\024\uffc5\025\uffc5\026\uffc5\027\uffc5\030\uffc5\031\uffc5" +
    "\032\uffc5\033\uffc5\034\uffc5\035\uffc5\036\uffc5\037\uffc5\040" +
    "\uffc5\001\002\000\042\003\uffc8\015\uffc8\020\uffc8\024\uffc8" +
    "\025\uffc8\026\061\027\064\030\uffc8\031\uffc8\032\uffc8\033" +
    "\uffc8\034\uffc8\035\uffc8\036\uffc8\037\uffc8\040\uffc8\001\002" +
    "\000\020\003\050\004\044\005\047\013\015\014\042\025" +
    "\043\041\051\001\002\000\042\003\uffcd\015\uffcd\020\uffcd" +
    "\024\063\025\054\026\061\027\064\030\uffcd\031\uffcd\032" +
    "\uffcd\033\uffcd\034\uffcd\035\uffcd\036\uffcd\037\uffcd\040\uffcd" +
    "\001\002\000\042\003\uffc6\015\uffc6\020\uffc6\024\uffc6\025" +
    "\uffc6\026\uffc6\027\uffc6\030\uffc6\031\uffc6\032\uffc6\033\uffc6" +
    "\034\uffc6\035\uffc6\036\uffc6\037\uffc6\040\uffc6\001\002\000" +
    "\042\003\uffc9\015\uffc9\020\uffc9\024\063\025\054\026\061" +
    "\027\064\030\070\031\066\032\057\033\056\034\065\035" +
    "\055\036\062\037\053\040\067\001\002\000\042\003\uffc7" +
    "\015\uffc7\020\uffc7\024\uffc7\025\uffc7\026\061\027\064\030" +
    "\uffc7\031\uffc7\032\uffc7\033\uffc7\034\uffc7\035\uffc7\036\uffc7" +
    "\037\uffc7\040\uffc7\001\002\000\042\003\uffd0\015\uffd0\020" +
    "\uffd0\024\063\025\054\026\061\027\064\030\070\031\066" +
    "\032\057\033\056\034\065\035\055\036\062\037\uffd0\040" +
    "\uffd0\001\002\000\024\002\uffe2\003\uffe2\006\uffe2\007\uffe2" +
    "\010\uffe2\012\uffe2\013\uffe2\016\uffe2\017\uffe2\001\002\000" +
    "\042\003\uffbf\015\uffbf\020\uffbf\024\uffbf\025\uffbf\026\uffbf" +
    "\027\uffbf\030\uffbf\031\uffbf\032\uffbf\033\uffbf\034\uffbf\035" +
    "\uffbf\036\uffbf\037\uffbf\040\uffbf\001\002\000\042\003\uffc0" +
    "\015\uffc0\020\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0\030" +
    "\uffc0\031\uffc0\032\uffc0\033\uffc0\034\uffc0\035\uffc0\036\uffc0" +
    "\037\uffc0\040\uffc0\001\002\000\036\015\114\024\063\025" +
    "\054\026\061\027\064\030\070\031\066\032\057\033\056" +
    "\034\065\035\055\036\062\037\053\040\067\001\002\000" +
    "\006\015\113\023\041\001\002\000\042\003\uffbe\015\uffbe" +
    "\020\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030\uffbe\031" +
    "\uffbe\032\uffbe\033\uffbe\034\uffbe\035\uffbe\036\uffbe\037\uffbe" +
    "\040\uffbe\001\002\000\042\003\uffc4\015\uffc4\020\uffc4\024" +
    "\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031\uffc4\032\uffc4" +
    "\033\uffc4\034\uffc4\035\uffc4\036\uffc4\037\uffc4\040\uffc4\001" +
    "\002\000\024\002\uffee\003\uffee\006\uffee\007\uffee\010\uffee" +
    "\012\uffee\013\uffee\016\uffee\017\uffee\001\002\000\022\002" +
    "\ufff2\003\ufff2\006\ufff2\007\ufff2\010\ufff2\013\ufff2\016\ufff2" +
    "\017\ufff2\001\002\000\010\020\037\023\041\036\036\001" +
    "\002\000\006\020\123\023\041\001\002\000\004\020\122" +
    "\001\002\000\024\002\uffe1\003\uffe1\006\uffe1\007\uffe1\010" +
    "\uffe1\012\uffe1\013\uffe1\016\uffe1\017\uffe1\001\002\000\024" +
    "\002\uffe0\003\uffe0\006\uffe0\007\uffe0\010\uffe0\012\uffe0\013" +
    "\uffe0\016\uffe0\017\uffe0\001\002\000\020\003\127\004\044" +
    "\005\047\013\015\014\042\025\043\041\051\001\002\000" +
    "\024\002\uffe5\003\uffe5\006\uffe5\007\uffe5\010\uffe5\012\uffe5" +
    "\013\uffe5\016\uffe5\017\uffe5\001\002\000\036\020\131\024" +
    "\063\025\054\026\061\027\064\030\070\031\066\032\057" +
    "\033\056\034\065\035\055\036\062\037\053\040\067\001" +
    "\002\000\006\020\130\023\041\001\002\000\024\002\uffe3" +
    "\003\uffe3\006\uffe3\007\uffe3\010\uffe3\012\uffe3\013\uffe3\016" +
    "\uffe3\017\uffe3\001\002\000\024\002\uffe4\003\uffe4\006\uffe4" +
    "\007\uffe4\010\uffe4\012\uffe4\013\uffe4\016\uffe4\017\uffe4\001" +
    "\002\000\006\004\134\013\133\001\002\000\004\023\136" +
    "\001\002\000\004\023\135\001\002\000\042\003\uffb8\015" +
    "\uffb8\020\uffb8\024\uffb8\025\uffb8\026\uffb8\027\uffb8\030\uffb8" +
    "\031\uffb8\032\uffb8\033\uffb8\034\uffb8\035\uffb8\036\uffb8\037" +
    "\uffb8\040\uffb8\001\002\000\042\003\uffb7\015\uffb7\020\uffb7" +
    "\024\uffb7\025\uffb7\026\uffb7\027\uffb7\030\uffb7\031\uffb7\032" +
    "\uffb7\033\uffb7\034\uffb7\035\uffb7\036\uffb7\037\uffb7\040\uffb7" +
    "\001\002\000\016\003\uffd8\006\uffd8\007\uffd8\010\uffd8\013" +
    "\uffd8\016\uffd8\001\002\000\020\003\050\004\044\005\047" +
    "\013\015\014\042\025\043\041\051\001\002\000\020\003" +
    "\143\004\044\005\047\013\015\014\042\025\043\041\051" +
    "\001\002\000\040\003\146\015\145\024\063\025\054\026" +
    "\061\027\064\030\070\031\066\032\057\033\056\034\065" +
    "\035\055\036\062\037\053\040\067\001\002\000\006\015" +
    "\144\023\041\001\002\000\016\003\uffdb\006\uffdb\007\uffdb" +
    "\010\uffdb\013\uffdb\016\uffdb\001\002\000\016\003\uffdc\006" +
    "\uffdc\007\uffdc\010\uffdc\013\uffdc\016\uffdc\001\002\000\016" +
    "\003\uffd9\006\uffd9\007\uffd9\010\uffd9\013\uffd9\016\uffd9\001" +
    "\002\000\036\015\150\024\063\025\054\026\061\027\064" +
    "\030\070\031\066\032\057\033\056\034\065\035\055\036" +
    "\062\037\053\040\067\001\002\000\016\003\uffda\006\uffda" +
    "\007\uffda\010\uffda\013\uffda\016\uffda\001\002\000\016\003" +
    "\155\006\022\007\014\010\013\013\015\016\154\001\002" +
    "\000\024\002\uffe7\003\uffe7\006\uffe7\007\uffe7\010\uffe7\012" +
    "\166\013\uffe7\016\uffe7\017\uffe7\001\002\000\004\012\157" +
    "\001\002\000\016\003\023\006\022\007\014\010\013\013" +
    "\015\016\026\001\002\000\006\023\041\036\036\001\002" +
    "\000\020\003\117\006\022\007\014\010\013\013\015\016" +
    "\026\017\033\001\002\000\016\003\uffd7\006\uffd7\007\uffd7" +
    "\010\uffd7\013\uffd7\016\uffd7\001\002\000\016\003\155\006" +
    "\022\007\162\010\013\013\015\016\154\001\002\000\024" +
    "\002\uffe6\003\uffe6\006\uffe6\007\uffe6\010\uffe6\012\uffe6\013" +
    "\uffe6\016\uffe6\017\uffe6\001\002\000\006\003\140\014\141" +
    "\001\002\000\016\003\uffd8\006\uffd8\007\uffd8\010\uffd8\013" +
    "\uffd8\016\uffd8\001\002\000\016\003\155\006\022\007\162" +
    "\010\013\013\015\016\154\001\002\000\004\012\166\001" +
    "\002\000\016\003\uffd7\006\uffd7\007\uffd7\010\uffd7\013\uffd7" +
    "\016\uffd7\001\002\000\016\003\155\006\022\007\162\010" +
    "\013\013\015\016\154\001\002\000\024\002\uffec\003\uffec" +
    "\006\uffec\007\uffec\010\uffec\012\uffec\013\uffec\016\uffec\017" +
    "\uffec\001\002\000\020\003\050\004\044\005\047\013\015" +
    "\014\042\025\043\041\051\001\002\000\020\003\177\004" +
    "\044\005\047\013\015\014\042\025\043\041\051\001\002" +
    "\000\016\003\uffd1\006\uffd1\007\uffd1\010\uffd1\013\uffd1\016" +
    "\uffd1\001\002\000\016\003\117\006\022\007\014\010\013" +
    "\013\015\016\026\001\002\000\024\002\uffd6\003\uffd6\006" +
    "\uffd6\007\uffd6\010\uffd6\012\uffd6\013\uffd6\016\uffd6\017\uffd6" +
    "\001\002\000\040\003\202\015\201\024\063\025\054\026" +
    "\061\027\064\030\070\031\066\032\057\033\056\034\065" +
    "\035\055\036\062\037\053\040\067\001\002\000\006\015" +
    "\200\023\041\001\002\000\016\003\uffd4\006\uffd4\007\uffd4" +
    "\010\uffd4\013\uffd4\016\uffd4\001\002\000\016\003\uffd5\006" +
    "\uffd5\007\uffd5\010\uffd5\013\uffd5\016\uffd5\001\002\000\016" +
    "\003\uffd2\006\uffd2\007\uffd2\010\uffd2\013\uffd2\016\uffd2\001" +
    "\002\000\036\015\204\024\063\025\054\026\061\027\064" +
    "\030\070\031\066\032\057\033\056\034\065\035\055\036" +
    "\062\037\053\040\067\001\002\000\016\003\uffd3\006\uffd3" +
    "\007\uffd3\010\uffd3\013\uffd3\016\uffd3\001\002\000\010\020" +
    "\ufff6\021\ufff6\022\216\001\002\000\006\020\213\021\212" +
    "\001\002\000\004\020\211\001\002\000\006\020\ufff9\021" +
    "\ufff9\001\002\000\022\003\ufffc\006\ufffc\007\ufffc\010\ufffc" +
    "\013\ufffc\016\ufffc\042\ufffc\043\ufffc\001\002\000\004\013" +
    "\ufff8\001\002\000\022\003\ufffd\006\ufffd\007\ufffd\010\ufffd" +
    "\013\ufffd\016\ufffd\042\ufffd\043\ufffd\001\002\000\004\013" +
    "\205\001\002\000\006\020\ufff7\021\ufff7\001\002\000\004" +
    "\004\217\001\002\000\004\023\220\001\002\000\006\020" +
    "\ufff5\021\ufff5\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\216\000\006\002\004\020\003\001\001\000\026\003" +
    "\015\004\027\005\020\006\007\012\017\017\016\021\010" +
    "\024\011\030\023\031\026\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\022\205\023\207\001\001\000\004\027" +
    "\172\001\001\000\004\026\136\001\001\000\002\001\001" +
    "\000\020\004\033\005\020\006\007\012\017\017\016\030" +
    "\023\031\026\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\012\120\001\001\000\020\004" +
    "\115\005\020\006\007\012\017\017\016\030\023\031\026" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\003" +
    "\031\004\027\005\020\006\007\012\017\017\016\030\023" +
    "\031\026\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\004\115\005\020\006\007\012\017\017\016\030\023" +
    "\031\026\001\001\000\020\004\033\005\020\006\007\012" +
    "\017\017\016\030\023\031\026\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\012\044\013" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\012\044\013\110\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\010\070" +
    "\011\057\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\044\013\051\001\001\000\006\010\070\011\057" +
    "\001\001\000\006\012\044\013\104\001\001\000\006\012" +
    "\044\013\103\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\012\044\013\102\001\001\000" +
    "\006\012\044\013\101\001\001\000\002\001\001\000\006" +
    "\012\044\013\076\001\001\000\006\012\044\013\075\001" +
    "\001\000\002\001\001\000\006\012\044\013\074\001\001" +
    "\000\006\012\044\013\073\001\001\000\006\012\044\013" +
    "\072\001\001\000\006\012\044\013\071\001\001\000\006" +
    "\010\070\011\057\001\001\000\006\010\070\011\057\001" +
    "\001\000\006\010\070\011\057\001\001\000\006\010\070" +
    "\011\057\001\001\000\006\010\070\011\057\001\001\000" +
    "\006\010\070\011\057\001\001\000\006\012\044\013\100" +
    "\001\001\000\006\010\070\011\057\001\001\000\006\010" +
    "\070\011\057\001\001\000\006\010\070\011\057\001\001" +
    "\000\006\010\070\011\057\001\001\000\006\010\070\011" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\010\070\011\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\012\044\013\125\001\001\000\002\001\001\000\006\010" +
    "\070\011\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\150\001\001\000\006\012\044\013\146\001\001\000" +
    "\006\012\044\013\141\001\001\000\006\010\070\011\057" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\010\070\011\057\001\001" +
    "\000\002\001\001\000\016\005\020\006\007\012\017\017" +
    "\016\030\151\031\152\001\001\000\002\001\001\000\002" +
    "\001\001\000\022\003\155\004\027\005\020\006\007\012" +
    "\017\017\016\030\023\031\026\001\001\000\002\001\001" +
    "\000\020\004\033\005\020\006\007\012\017\017\016\030" +
    "\023\031\026\001\001\000\004\016\157\001\001\000\014" +
    "\005\020\006\007\012\017\017\016\030\160\001\001\000" +
    "\002\001\001\000\004\026\162\001\001\000\004\015\163" +
    "\001\001\000\014\005\020\006\007\012\017\017\016\030" +
    "\164\001\001\000\002\001\001\000\004\016\166\001\001" +
    "\000\014\005\020\006\007\012\017\017\016\030\167\001" +
    "\001\000\002\001\001\000\006\012\044\013\202\001\001" +
    "\000\006\012\044\013\175\001\001\000\004\014\173\001" +
    "\001\000\020\004\174\005\020\006\007\012\017\017\016" +
    "\030\023\031\026\001\001\000\002\001\001\000\006\010" +
    "\070\011\057\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\010\070\011" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\032\213\001\001\000\002\001\001\000\004" +
    "\023\214\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {

    // buffer che conterrà l'output program
    outputBuffer = new StringBuffer();
    errorBuffer = new StringBuffer();

 Tree = new DisegnaAlbero();   }public static DisegnaAlbero Tree;

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 Symbol s=_scanner.next_token(); Tree.push(s.toString(), 0); return s;   }



    HashMap<String, SymbolType> SymbolType_table = new HashMap<String, SymbolType>();

    // numero della first usable label
    public int label = 0;

    // file di output (stdout oppure file [to dumb program in a file])
    public static String dumpOutput;

    // true se il semantic check è attivo
    public boolean enableSem = true;

    public int semError = 0;
    public int semWarnings = 0;
    public int synWarnings = 0;
    // string buffer per l'output program (inizializzato sopra con init)
    public StringBuffer outputBuffer;
    public StringBuffer errorBuffer;
    // generazione del numero della next label
    public int genLabel(){
        label++;
        return label;
    }
    
    // Redefinition of error functions
    public void report_error(String message, Object info) {
        System.err.print("ERROR: Syntax error");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.print(" (linea "+line+", colonna "+column+"): ");
            } else System.err.print(": ");
        else System.err.print(": ");
    }
    public void syntax_error(Symbol cur_token){}

    // ritorna actual symbol (tos = top of stack) [dalla teoria]
    public Symbol getToken() {
        return ((Symbol)stack.elementAt(tos));
    }

    // ritorna il semantic value del simbolo alla posizione pos [dalla teoria]
    public Object stack(int pos) {
        return (((Symbol)stack.elementAt(tos + pos)).value);
    }

    // Return the line number of actual symbol
    public int getLine() {
        if (((Symbol)stack.elementAt(tos)).left != -1){
            return ((Symbol)stack.elementAt(tos)).left+1;
        }else return -1;
    }
    // Return the column number of actual symbol
    public int getColumn() {
        if (((Symbol)stack.elementAt(tos)).left != -1){
            return ((Symbol)stack.elementAt(tos)).right+1;
        }else return -1;
    }

    // Classe SymbolType minima per compilazione
    class SymbolType {
        private int type;
        private int dim;
        public SymbolType(int type, int dim) {
            this.type = type;
            this.dim = dim;
        }
        public int getType() { return type; }
        public int getDim() { return dim; }
        public String getName() {
            if(type == 0) return "INT";
            if(type == 1) return "DOUBLE";
            return "UNDEFINED";
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {



    class Expr{
        private String value;
        private SymbolType type;

        private SymbolType lookupSymbolType(String id) {
            SymbolType st = parser.SymbolType_table.get(id);
            if (st == null) {
                pSemError("Symbol '" + id + "' not declared");
                return new SymbolType(-1, -1);
            }
            return st;
        }

        Expr(String value, SymbolType type) {
            this.value = value;
            this.type = type;
        }

        Expr(String value) {
            this.value = value;
            this.type = lookupSymbolType(value); // tipo non definito
        }

        Expr(String value, Integer pos) {
            this.value = value+"["+pos.toString()+"]";
            this.type = lookupSymbolType(value);
            int dim = type.getDim();
            if(pos >= dim && dim != -1) {
                pSemError("Index out of bounds for array '" + value + "': " + pos);
            }
        }

        Expr(String value, String pos) {
            this.value = value+"["+pos+"]";
            this.type = lookupSymbolType(value);
        }

        public String toString() {
            return value;
        }

        public SymbolType getSymbolType() {
            return type;
        }

        public SymbolType checkType(Expr e){
            int type1 = type.getType();
            int type2 = e.getSymbolType().getType();
            if(type1 == type2){
                return type;
            } else if (type1 != -1 && type2 != -1) {
                pSemWarning("Type mismatch: " + type.getName() + " and " + e.getSymbolType().getName());
                return new SymbolType(-1, -1); // tipo non definito
            }
            else{
                return new SymbolType(-1, -1); // tipo non definito
            }
        }

        public void checkSymbolTypeAssignment(Expr e){
            int type1 = type.getType();
            int type2 = e.getSymbolType().getType();
            if(type1 == 0 && type2 == 1){
                 pSemWarning("Assignment from DOUBLE to INT: " + type.getName() + " to " + e.getSymbolType().getName());
            } else if (type1 == 1 && type2 == 0) {
                pSemWarning("Assignment from INT to DOUBLE: " + type.getName() + " to " + e.getSymbolType().getName());
            }
        }
    }


    // disabilita semantic check
    private void disableSem() {
        parser.enableSem = false;
    }
    // ritorna true se semantic check è attivo (o no)
    private boolean sem() {
        return parser.enableSem;
    }

    // Error Management
    private void pSemError(String message){
        parser.errorBuffer.append("SEM ERROR: line: "+parser.getLine()+" col: "+parser.getColumn()+": "+message+"\n");
        parser.semError++;
    }
    private void pSemWarning(String message){
        parser.errorBuffer.append("SEM WARNING: line: "+parser.getLine()+" col: "+parser.getColumn()+": "+message+"\n");
        parser.semWarnings++;
    }
    private void pSynError(String message){
        System.err.println("SYN ERROR: line:"+parser.getLine()+" col:"+parser.getColumn()+": "+message);
        System.err.println("Could not continue parsing");
        parser.done_parsing();
    }
    private void pSynWarning(String message){
        parser.errorBuffer.append("SYN WARNING: line: "+parser.getLine()+" col: "+parser.getColumn()+": "+message+"\n");
        parser.synWarnings++;
        disableSem(); // se c'è errore sintattico disabilito semantica
    }

    // scrive una String in output
    private void dump(String s){
        if(parser.dumpOutput == "stdout") {System.out.print(s);}
        else {parser.outputBuffer.append(s);}
    }
    private void dumpln(String s){
        if(parser.dumpOutput == "stdout") System.out.println(s);
        else parser.outputBuffer.append(s+"\n");
    } 

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= prog EOF 
            { 
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // prog ::= decl_list stmt_list 
            { parser.Tree.reduce(2,"prog",0);
              Object RESULT =null;
		
                if(sem() && parser.semError == 0) {
                    dumpln("\n// Program successfully parsed");
                    if (parser.dumpOutput == "stdout") {
                        System.out.println(parser.outputBuffer.toString());
                    } else {
                        try {
                            BufferedWriter writer = new BufferedWriter(new FileWriter(parser.dumpOutput));
                            String output = parser.outputBuffer.toString();
                            writer.write(output);
                            writer.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                        
                    }
                } else {
                    System.err.println("\n// Program parsing failed with " + parser.semError + " errors and " + parser.semWarnings + " warnings.");
                }
                System.err.println(parser.errorBuffer);
                System.err.println("Total syntax warnings: " + parser.synWarnings);
                System.err.println("Total semantic errors: " + parser.semError);
                System.err.println("Total semantic warnings: " + parser.semWarnings);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // decl_list ::= decl_list decl 
            { parser.Tree.reduce(2,"decl_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_list",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // decl_list ::= 
            { parser.Tree.reduce(0,"decl_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_list",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // decl ::= type var_list S 
            { parser.Tree.reduce(3,"decl",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // decl ::= type error S 
            { parser.Tree.reduce(3,"decl",0);
              Object RESULT =null;
		 pSynWarning("Error in declaration"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // type ::= INT_TYPE 
            { parser.Tree.reduce(1,"type",0);
              String RESULT =null;
		 if(sem()) RESULT = new String("INT"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // type ::= DOUBLE_TYPE 
            { parser.Tree.reduce(1,"type",0);
              String RESULT =null;
		 if(sem()) RESULT = new String("DOUBLE"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // var_list ::= var 
            { parser.Tree.reduce(1,"var_list",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$0 ::= 
            { parser.Tree.reduce(0,"NT$0",0);
              Object RESULT =null;
 if(sem()) RESULT = parser.stack(-2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // var_list ::= var_list CM NT$0 var 
            { parser.Tree.reduce(4,"var_list",0);
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("var_list",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // var ::= ID 
            { parser.Tree.reduce(1,"var",0);
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) {
    dumpln("\t"+parser.stack(-1) + " " + x);
    if(parser.stack(-1).equals("INT")) {
        parser.SymbolType_table.put(x, new SymbolType(0, 1)); // INT type
    } else if(parser.stack(-1).equals("DOUBLE")) {
        parser.SymbolType_table.put(x, new SymbolType(1, 1)); // DOUBLE type
    }
}
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // var ::= ID SO INT SC 
            { parser.Tree.reduce(4,"var",0);
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer y = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(sem()) {
    dumpln("\t"+parser.stack(-4) + " " + x + "[" + y.toString() + "]");
    if(parser.stack(-4).equals("INT")) {
        parser.SymbolType_table.put(x, new SymbolType(0, y)); // INT array
    } else if(parser.stack(-4).equals("DOUBLE")) {
        parser.SymbolType_table.put(x, new SymbolType(1, y)); // DOUBLE array
    }
}
              CUP$parser$result = parser.getSymbolFactory().newSymbol("var",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // stmt_list ::= stmt_list stmt 
            { parser.Tree.reduce(2,"stmt_list",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // stmt_list ::= stmt 
            { parser.Tree.reduce(1,"stmt_list",1);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // stmt_list ::= error stmt 
            { parser.Tree.reduce(2,"stmt_list",1);
              Object RESULT =null;
		 pSynWarning("Error in statement"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // stmt ::= matched_stmt 
            { parser.Tree.reduce(1,"stmt",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // stmt ::= unmatched_stmt 
            { parser.Tree.reduce(1,"stmt",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // stmt ::= BO stmt_list error BC 
            { parser.Tree.reduce(4,"stmt",0);
              Object RESULT =null;
		 pSynWarning("Missing ; before }"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // stmt ::= BO error BC 
            { parser.Tree.reduce(3,"stmt",0);
              Object RESULT =null;
		 pSynWarning("Missing ; before }"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // stmt ::= error S 
            { parser.Tree.reduce(2,"stmt",0);
              Object RESULT =null;
		 pSynWarning("Error in statement"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // matched_stmt ::= IF if_condition nt0_if matched_stmt ELSE nt1_if matched_stmt 
            { parser.Tree.reduce(7,"matched_stmt",0);
              Object RESULT =null;
		
                    if (sem()) {dump("L" + parser.stack(-1) + ":");}
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("matched_stmt",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // matched_stmt ::= while 
            { parser.Tree.reduce(1,"matched_stmt",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("matched_stmt",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // matched_stmt ::= assignment 
            { parser.Tree.reduce(1,"matched_stmt",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("matched_stmt",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // matched_stmt ::= print 
            { parser.Tree.reduce(1,"matched_stmt",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("matched_stmt",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // matched_stmt ::= BO stmt_list BC 
            { parser.Tree.reduce(3,"matched_stmt",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("matched_stmt",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // unmatched_stmt ::= IF if_condition nt0_if matched_stmt 
            { parser.Tree.reduce(4,"unmatched_stmt",0);
              Object RESULT =null;
		 if (sem()) {dump("L" + parser.stack(-1) + ":");} 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("unmatched_stmt",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // unmatched_stmt ::= IF if_condition nt0_if unmatched_stmt ELSE nt1_if matched_stmt 
            { parser.Tree.reduce(7,"unmatched_stmt",0);
              Object RESULT =null;
		 if (sem()) {dump("L" + parser.stack(-1) + ":");} 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("unmatched_stmt",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // assignment ::= id S 
            { parser.Tree.reduce(2,"assignment",0);
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if (sem()) {dumpln("\t" + x);} 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // assignment ::= id EQ exp S 
            { parser.Tree.reduce(4,"assignment",0);
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if (sem()) {x.checkSymbolTypeAssignment(y); dumpln("\tEVAL "+y+"\n\tASS "+x);} 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // assignment ::= id EQ error S 
            { parser.Tree.reduce(4,"assignment",0);
              Object RESULT =null;
		 pSynWarning("Error in expression"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // assignment ::= error EQ exp S 
            { parser.Tree.reduce(4,"assignment",0);
              Object RESULT =null;
		 pSynWarning("Error in assigment"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // print ::= PRINT id S 
            { parser.Tree.reduce(3,"print",0);
              Object RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if (sem()) {dumpln("\tPRINT " + x);} 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("print",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // print ::= PRINT error S 
            { parser.Tree.reduce(3,"print",0);
              Object RESULT =null;
		 pSynWarning("Error in 'print' instruction"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("print",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // if ::= IF if_condition nt0_if stmt ELSE nt1_if stmt 
            { parser.Tree.reduce(7,"if",0);
              Object RESULT =null;
		
                                if (sem()) {dump("L" + parser.stack(-1) + ":");}
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // if ::= IF if_condition nt0_if stmt 
            { parser.Tree.reduce(4,"if",0);
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
                                if (sem()) {dump("L" + parser.stack(-1) + ":");}
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // if ::= IF if_condition nt0_if stmt error nt1_if stmt 
            { parser.Tree.reduce(7,"if",0);
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		 pSynWarning("Error 'else' expected in 'if' instruction"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // if_condition ::= RO exp RC 
            { parser.Tree.reduce(3,"if_condition",0);
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(sem()) RESULT=e.value; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_condition",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // if_condition ::= RO error RC 
            { parser.Tree.reduce(3,"if_condition",0);
              String RESULT =null;
		 pSynWarning("Error in 'if' condition"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_condition",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // if_condition ::= error exp RC 
            { parser.Tree.reduce(3,"if_condition",0);
              String RESULT =null;
		 pSynWarning("Error '(' expected in 'if' instruciton"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_condition",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // if_condition ::= RO exp error 
            { parser.Tree.reduce(3,"if_condition",0);
              String RESULT =null;
		 pSynWarning("Error ')' expected in 'if' instruciton"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_condition",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // nt0_if ::= 
            { parser.Tree.reduce(0,"nt0_if",0);
              Integer RESULT =null;
		
        if (sem()) {
            RESULT = parser.genLabel();
            dumpln("\tEVAL " + parser.stack(0) + "\t\t/* if (line " + parser.getLine() + ") */\n\tGOTOF L" + RESULT);
        }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nt0_if",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // nt1_if ::= 
            { parser.Tree.reduce(0,"nt1_if",0);
              Integer RESULT =null;
		
        if (sem()) {
            RESULT = parser.genLabel();
            dumpln("\tGOTO L" + RESULT);
            dump("L" + parser.stack(-2) + ":");
        }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nt1_if",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // while ::= WHILE while_condition nt0_while stmt 
            { parser.Tree.reduce(4,"while",0);
              Object RESULT =null;
		
                    if (sem()) {
                        Integer[] l = (Integer[])parser.stack(-1);
                        dumpln("\tGOTO L" + l[0]);
                        dump("L" + l[1] + ":");
                    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("while",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // while_condition ::= RO exp RC 
            { parser.Tree.reduce(3,"while_condition",0);
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr e = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(sem()) RESULT=e.value; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_condition",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // while_condition ::= RO error RC 
            { parser.Tree.reduce(3,"while_condition",0);
              String RESULT =null;
		 pSynWarning("Error in 'while' condition"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_condition",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // while_condition ::= error exp RC 
            { parser.Tree.reduce(3,"while_condition",0);
              String RESULT =null;
		 pSynWarning("Error '(' expected in 'while' instruciton"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_condition",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // while_condition ::= RO exp error 
            { parser.Tree.reduce(3,"while_condition",0);
              String RESULT =null;
		 pSynWarning("Error ')' expected in 'while' instruciton"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_condition",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // nt0_while ::= 
            { parser.Tree.reduce(0,"nt0_while",0);
              Integer[] RESULT =null;
		
        if (sem()) {
            RESULT = new Integer[2];
            RESULT[0] = (Integer)parser.genLabel();
            RESULT[1] = (Integer)parser.genLabel();
            dumpln("L" + RESULT[0] + ":\tEVAL " + parser.stack(0) + "\t\t/* while (line " + parser.getLine() + ") */\n\tGOTOF L" + RESULT[1]);
        }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("nt0_while",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // exp ::= exp AND exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"&", x.checkType(y));
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // exp ::= exp OR exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		if(sem()) RESULT = new Expr(x+" "+y+"|", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // exp ::= NOT exp 
            { parser.Tree.reduce(2,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+"!", x.getSymbolType()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // exp ::= exp EQ EQ exp 
            { parser.Tree.reduce(4,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"==", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // exp ::= exp MIN exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"<", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // exp ::= exp MAJ exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+">", x.checkType(y));; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // exp ::= exp mineq exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"<=", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // exp ::= exp majeq exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+">=", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // exp ::= exp PLUS exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"+", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // exp ::= exp MINUS exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"-", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // exp ::= exp STAR exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"*", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // exp ::= exp DIV exp 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr y = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x+" "+y+"/", x.checkType(y)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exp ::= RO exp RC 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(sem()) RESULT = x; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // exp ::= id 
            { parser.Tree.reduce(1,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expr x = (Expr)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = x; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // exp ::= INT 
            { parser.Tree.reduce(1,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer x = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x.toString(), new SymbolType(0,1)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // exp ::= DOUBLE 
            { parser.Tree.reduce(1,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double x = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x.toString(), new SymbolType(1,1)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // exp ::= MINUS INT 
            { parser.Tree.reduce(2,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer x = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr("-"+x.toString(), new SymbolType(0,1)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // exp ::= MINUS DOUBLE 
            { parser.Tree.reduce(2,"exp",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double x = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr("-"+x.toString(), new SymbolType(1,1)); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // exp ::= RO error RC 
            { parser.Tree.reduce(3,"exp",0);
              Expr RESULT =null;
		 pSynWarning("Error in expression"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("exp",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // mineq ::= MIN_EQ 
            { parser.Tree.reduce(1,"mineq",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("mineq",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // mineq ::= EQ_MIN 
            { parser.Tree.reduce(1,"mineq",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("mineq",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // majeq ::= MAJ_EQ 
            { parser.Tree.reduce(1,"majeq",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("majeq",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // majeq ::= EQ_MAJ 
            { parser.Tree.reduce(1,"majeq",0);
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("majeq",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // id ::= ID 
            { parser.Tree.reduce(1,"id",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 if(sem()) RESULT = new Expr(x); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // id ::= ID SO INT SC 
            { parser.Tree.reduce(4,"id",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer y = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(sem()) RESULT = new Expr(x, y); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // id ::= ID SO ID SC 
            { parser.Tree.reduce(4,"id",0);
              Expr RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 if(sem()) RESULT = new Expr(x, y); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // id ::= error SC 
            { parser.Tree.reduce(2,"id",0);
              Expr RESULT =null;
		 pSynWarning("Error in vector"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("id",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
