
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int OR = 18;
  public static final int QC = 6;
  public static final int TC = 8;
  public static final int V = 3;
  public static final int QA = 5;
  public static final int TA = 7;
  public static final int T = 13;
  public static final int NOT = 19;
  public static final int WITH = 15;
  public static final int PV = 2;
  public static final int F = 14;
  public static final int EOF = 0;
  public static final int CMP = 12;
  public static final int TOK3 = 11;
  public static final int TOK2 = 10;
  public static final int SEP = 21;
  public static final int TOK1 = 9;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int STR = 23;
  public static final int EQ = 4;
  public static final int FZ = 20;
  public static final int VAR = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PV",
  "V",
  "EQ",
  "QA",
  "QC",
  "TA",
  "TC",
  "TOK1",
  "TOK2",
  "TOK3",
  "CMP",
  "T",
  "F",
  "WITH",
  "PRINT",
  "AND",
  "OR",
  "NOT",
  "FZ",
  "SEP",
  "VAR",
  "STR"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[17]=new String("AND");
		TT[18]=new String("OR");
		TT[6]=new String("QC");
		TT[8]=new String("TC");
		TT[3]=new String("V");
		TT[5]=new String("QA");
		TT[7]=new String("TA");
		TT[13]=new String("T");
		TT[19]=new String("NOT");
		TT[15]=new String("WITH");
		TT[2]=new String("PV");
		TT[14]=new String("F");
		TT[0]=new String("EOF");
		TT[12]=new String("CMP");
		TT[11]=new String("TOK3");
		TT[10]=new String("TOK2");
		TT[21]=new String("SEP");
		TT[9]=new String("TOK1");
		TT[16]=new String("PRINT");
		TT[1]=new String("error");
		TT[23]=new String("STR");
		TT[4]=new String("EQ");
		TT[20]=new String("FZ");
		TT[22]=new String("VAR");
	}
public String getTT(int i){return TT[i];}
}

