
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 20;
  public static final int TC = 6;
  public static final int V = 7;
  public static final int TA = 5;
  public static final int M = 16;
  public static final int PV = 2;
  public static final int DP = 9;
  public static final int MS = 15;
  public static final int EOF = 0;
  public static final int TOK3 = 14;
  public static final int TOK2 = 13;
  public static final int SEP = 19;
  public static final int TOK1 = 12;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int ARROW = 11;
  public static final int GC = 4;
  public static final int STR = 21;
  public static final int EQ = 10;
  public static final int GA = 3;
  public static final int BAR = 8;
  public static final int PART = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PV",
  "GA",
  "GC",
  "TA",
  "TC",
  "V",
  "BAR",
  "DP",
  "EQ",
  "ARROW",
  "TOK1",
  "TOK2",
  "TOK3",
  "MS",
  "M",
  "PRINT",
  "PART",
  "SEP",
  "INT",
  "STR"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[20]=new String("INT");
		TT[6]=new String("TC");
		TT[7]=new String("V");
		TT[5]=new String("TA");
		TT[16]=new String("M");
		TT[2]=new String("PV");
		TT[9]=new String("DP");
		TT[15]=new String("MS");
		TT[0]=new String("EOF");
		TT[14]=new String("TOK3");
		TT[13]=new String("TOK2");
		TT[19]=new String("SEP");
		TT[12]=new String("TOK1");
		TT[17]=new String("PRINT");
		TT[1]=new String("error");
		TT[11]=new String("ARROW");
		TT[4]=new String("GC");
		TT[21]=new String("STR");
		TT[10]=new String("EQ");
		TT[3]=new String("GA");
		TT[8]=new String("BAR");
		TT[18]=new String("PART");
	}
public String getTT(int i){return TT[i];}
}

