
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int INT = 22;
  public static final int OR = 18;
  public static final int TC = 7;
  public static final int THEN = 15;
  public static final int V = 3;
  public static final int TA = 6;
  public static final int NOT = 19;
  public static final int END = 13;
  public static final int FI = 16;
  public static final int P = 5;
  public static final int IF = 14;
  public static final int DEQ = 4;
  public static final int PV = 2;
  public static final int ST = 12;
  public static final int EOF = 0;
  public static final int TOK3 = 10;
  public static final int TOK2 = 9;
  public static final int SEP = 21;
  public static final int TOK1 = 8;
  public static final int PRINT = 20;
  public static final int error = 1;
  public static final int STR = 23;
  public static final int HOUSE = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PV",
  "V",
  "DEQ",
  "P",
  "TA",
  "TC",
  "TOK1",
  "TOK2",
  "TOK3",
  "HOUSE",
  "ST",
  "END",
  "IF",
  "THEN",
  "FI",
  "AND",
  "OR",
  "NOT",
  "PRINT",
  "SEP",
  "INT",
  "STR"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[17]=new String("AND");
		TT[22]=new String("INT");
		TT[18]=new String("OR");
		TT[7]=new String("TC");
		TT[15]=new String("THEN");
		TT[3]=new String("V");
		TT[6]=new String("TA");
		TT[19]=new String("NOT");
		TT[13]=new String("END");
		TT[16]=new String("FI");
		TT[5]=new String("P");
		TT[14]=new String("IF");
		TT[4]=new String("DEQ");
		TT[2]=new String("PV");
		TT[12]=new String("ST");
		TT[0]=new String("EOF");
		TT[10]=new String("TOK3");
		TT[9]=new String("TOK2");
		TT[21]=new String("SEP");
		TT[8]=new String("TOK1");
		TT[20]=new String("PRINT");
		TT[1]=new String("error");
		TT[23]=new String("STR");
		TT[11]=new String("HOUSE");
	}
public String getTT(int i){return TT[i];}
}

