
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 14;
  public static final int INT = 23;
  public static final int OR = 15;
  public static final int TC = 7;
  public static final int V = 3;
  public static final int TA = 6;
  public static final int NOT = 16;
  public static final int END = 13;
  public static final int P = 8;
  public static final int NAME = 12;
  public static final int TRUE = 19;
  public static final int PV = 2;
  public static final int EOF = 0;
  public static final int OBJ = 11;
  public static final int TOK2 = 10;
  public static final int SEP = 22;
  public static final int FALSE = 20;
  public static final int TOK1 = 9;
  public static final int PRINT = 21;
  public static final int error = 1;
  public static final int STR = 24;
  public static final int EQ = 17;
  public static final int MINDOM = 5;
  public static final int DOM = 4;
  public static final int NEQ = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PV",
  "V",
  "DOM",
  "MINDOM",
  "TA",
  "TC",
  "P",
  "TOK1",
  "TOK2",
  "OBJ",
  "NAME",
  "END",
  "AND",
  "OR",
  "NOT",
  "EQ",
  "NEQ",
  "TRUE",
  "FALSE",
  "PRINT",
  "SEP",
  "INT",
  "STR"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[14]=new String("AND");
		TT[23]=new String("INT");
		TT[15]=new String("OR");
		TT[7]=new String("TC");
		TT[3]=new String("V");
		TT[6]=new String("TA");
		TT[16]=new String("NOT");
		TT[13]=new String("END");
		TT[8]=new String("P");
		TT[12]=new String("NAME");
		TT[19]=new String("TRUE");
		TT[2]=new String("PV");
		TT[0]=new String("EOF");
		TT[11]=new String("OBJ");
		TT[10]=new String("TOK2");
		TT[22]=new String("SEP");
		TT[20]=new String("FALSE");
		TT[9]=new String("TOK1");
		TT[21]=new String("PRINT");
		TT[1]=new String("error");
		TT[24]=new String("STR");
		TT[17]=new String("EQ");
		TT[5]=new String("MINDOM");
		TT[4]=new String("DOM");
		TT[18]=new String("NEQ");
	}
public String getTT(int i){return TT[i];}
}

